### ISSUE TITLE
Permission denied when trying to install new nodes from the palette ui

### ISSUE THREAD

**Issue by tekos-flow** [binnes/Node-RED-Docker#2]
Hello, 
I have deployed the service at AWS ECS, and when I try to install additional nodes from the Node Red Palette UI, i have got this error message
Error: EACCES: permission denied, access '/home/nodered/.node-red/node_modules

I tried several tricks to solve this by giving the user nodered access but i have failed.
Any idea in how we can fix this permission issue ?
Thanks

**Comment by binnes** [comment]
Hello,  This image is not meant to be a development image.  It is part of a workshop to show how to package a Node-RED application into a container for production use  - which should have the editor turned off.

However, I've made a change to the Dockerfile and settings.js to move the Node-RED userDir from the nodered user directory to a new directory /data, which should resolve the permissions issue.  I would recommend you follow the Node-RED docker getting started guidelines if you want a development environment on Amazon (https://nodered.org/docs/getting-started/aws)
